name: Benchmark (Linux)

on: [push, pull_request]

jobs:
  check_benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Check benchmark
        uses: actions-rs/cargo@v1
        with:
          command: bench
